spring.application.name=api-gateway-auth

spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5433}/${AUTH_DB_NAME:auth_db}
spring.datasource.username=${AUTH_DB_USER:studymind}
spring.datasource.password=${AUTH_DB_PASSWORD:studymind}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
